# Data Cleaning
In this notebook, I lay out the steps I took to properly read the full Leiden Weibo Corpus CSV file as a pandas dataframe and clean aspects of the data which include: selecting certain columns, removing extraneous characters, removing rows that were incorrectly parsed by `pandas.read_csv`, changing data types of the corpus, and writing subsets of the data to various CSV files for future analysis.

In [1]:
# import required libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
sns.set(style="darkgrid")

In [2]:
# assign columns
col_names = ["col" + str(i) for i in range(1,10)]
# load full data set and convert csv \N to NaN in pandas dataframe
AllData = pd.read_csv('lwc_data\parsed_messages.csv', quotechar='\"', names=col_names, na_values='\\N')

In [3]:
AllData.head()

,col1,col2,col3,col4,col5,col6,col7,col8,col9
0,"""3399658666084059""","""44""","""1""","""m""","""soulleoo""","""一分耕耘，一分收获！//@soulleoo 的小小乐园的最具吸引力乐园为5031，超过@败...","""25""","""一 分 耕耘 ， 一 分 收获 ！ 的 小小 乐园 的 最 具 吸引力 乐园 为 5031...","""一/CD 分/M 耕耘/VV ，/PU 一/CD 分/M 收获/NN ！/PU 的/DEG..."
1,"""3399658666083922""","""35""","""1""","""m""","""Tony_Heqi""","""太给力了，是不是？//@Tony_Heqi 在达人麻将 获得了成就Good Job!，获取...","""36""","""太 给力 了 ， 是 不 是 ？ 在 达人 麻将 获得 了 成就 Good Job ， 获...","""太/AD 给力/VV 了/AS ，/PU 是/VC 不/AD 是/VC ？/PU 在/P ..."
2,"""3399658665799759""","""44""","""8""","""f""","""謝秋如""","""3399658665799719""",NaN,NaN,NaN
3,"""3399658665799554""","""44""","""3""","""m""","""yinjiawei""","""3399658665799504""",NaN,NaN,NaN
4,"""3399658665575454""","""31""","""1000""","""m""","""Wings_of_Winds""","""为什么每次不在中国都会在他们家？@田鸡W @-RJ-爱喝乙醇的甲醇""","""12""","""为什么 每 次 不 在 中国 都 会 在 他们 家 ？""","""为什么/AD 每/DT 次/M 不/AD 在/P 中国/NR 都/AD 会/VV 在/P ..."

These are the columns of the full data set as noted on the Leiden Weibo Corpus [website](http://lwc.daanvanesch.nl/openaccess.php).

In [4]:
# rename columns
AllData.columns = ['MessageID', 'Province', 'City', 'Gender', 'Username', 'Message', 'NumWords', 'WithWordBounds', 'POStags']

In [5]:
AllData.head()

,MessageID,Province,City,Gender,Username,Message,NumWords,WithWordBounds,POStags
0,"""3399658666084059""","""44""","""1""","""m""","""soulleoo""","""一分耕耘，一分收获！//@soulleoo 的小小乐园的最具吸引力乐园为5031，超过@败...","""25""","""一 分 耕耘 ， 一 分 收获 ！ 的 小小 乐园 的 最 具 吸引力 乐园 为 5031...","""一/CD 分/M 耕耘/VV ，/PU 一/CD 分/M 收获/NN ！/PU 的/DEG..."
1,"""3399658666083922""","""35""","""1""","""m""","""Tony_Heqi""","""太给力了，是不是？//@Tony_Heqi 在达人麻将 获得了成就Good Job!，获取...","""36""","""太 给力 了 ， 是 不 是 ？ 在 达人 麻将 获得 了 成就 Good Job ， 获...","""太/AD 给力/VV 了/AS ，/PU 是/VC 不/AD 是/VC ？/PU 在/P ..."
2,"""3399658665799759""","""44""","""8""","""f""","""謝秋如""","""3399658665799719""",NaN,NaN,NaN
3,"""3399658665799554""","""44""","""3""","""m""","""yinjiawei""","""3399658665799504""",NaN,NaN,NaN
4,"""3399658665575454""","""31""","""1000""","""m""","""Wings_of_Winds""","""为什么每次不在中国都会在他们家？@田鸡W @-RJ-爱喝乙醇的甲醇""","""12""","""为什么 每 次 不 在 中国 都 会 在 他们 家 ？""","""为什么/AD 每/DT 次/M 不/AD 在/P 中国/NR 都/AD 会/VV 在/P ..."

In [6]:
AllData.tail()

,MessageID,Province,City,Gender,Username,Message,NumWords,WithWordBounds,POStags
5103591,"""3407331444661006""","""32""","""1""","""f""","""damondede""","""还是烦，我在烦恼什么却不清楚""",NaN,NaN,NaN
5103592,"""3407331444404506""","""44""","""13""","""m""","""陈乐明_希望如此""","""呜呜！手手！掉扣了！！[泪][泪][衰] 今天吃一个苹果 手就掉扣了！一天一苹果医生接...",NaN,NaN,NaN
5103593,"""3407331444369205""","""11""","""1000""","""m""","""黄硕harry""","""-_","发现出处了，上微博的人不会不知道这个表情的....哈哈哈哈[喝多了]""",NaN,NaN
5103594,"""3407331444369201""","""44""","""7""","""m""","""Long_love""","""分享图片[黑线]""",NaN,NaN,NaN
5103595,"""3407331443121006""","""31""","""1000""","""f""","""极品ET""","""有种说法，25岁是个界限，这以后别轻易换恋人，因为性格已经定型，很难再与他人磨合。在看戏这...",NaN,NaN,NaN

## Various Cleaning Endeavors
Some entries in the original CSV are strings with commas in them. This in turn appears to manifest as an error in how pandas reads the CSV file as a dataframe. This should be taken into account with all future assumptions of the data. 

### Subsetting the Data
Going forward only the message and demographic data are important so I select the following columns.

In [7]:
# subset message and demographic data
AllMessages = AllData[['MessageID', 'Province', 'City', 'Gender', 'Message']]

In [8]:
AllMessages.head()

,MessageID,Province,City,Gender,Message
0,"""3399658666084059""","""44""","""1""","""m""","""一分耕耘，一分收获！//@soulleoo 的小小乐园的最具吸引力乐园为5031，超过@败..."
1,"""3399658666083922""","""35""","""1""","""m""","""太给力了，是不是？//@Tony_Heqi 在达人麻将 获得了成就Good Job!，获取..."
2,"""3399658665799759""","""44""","""8""","""f""","""3399658665799719"""
3,"""3399658665799554""","""44""","""3""","""m""","""3399658665799504"""
4,"""3399658665575454""","""31""","""1000""","""m""","""为什么每次不在中国都会在他们家？@田鸡W @-RJ-爱喝乙醇的甲醇"""

### Removing Extraneous Characters
In the original CSV file, each entry is encapsulate by double quotes (i.e. "content") despite being initialized as strings by default, thus, I strip these characters initially.

In [9]:
# remove extraneous double quotes 
AllMessages['MessageID'] = AllMessages['MessageID'].str.replace("\"", "")
AllMessages['Province'] = AllMessages['Province'].str.replace("\"", "")
AllMessages['City'] = AllMessages['City'].str.replace("\"", "")
AllMessages['Gender'] = AllMessages['Gender'].str.replace("\"", "")
AllMessages['Message'] = AllMessages['Message'].str.replace("\"", "")

C:\Users\hobbs\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\hobbs\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\hobbs\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\hobbs\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\hobbs\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [10]:
AllMessages.head()

,MessageID,Province,City,Gender,Message
0,3399658666084059,44,1,m,一分耕耘，一分收获！//@soulleoo 的小小乐园的最具吸引力乐园为5031，超过@败家...
1,3399658666083922,35,1,m,太给力了，是不是？//@Tony_Heqi 在达人麻将 获得了成就Good Job!，获取速...
2,3399658665799759,44,8,f,3399658665799719
3,3399658665799554,44,3,m,3399658665799504
4,3399658665575454,31,1000,m,为什么每次不在中国都会在他们家？@田鸡W @-RJ-爱喝乙醇的甲醇

### Removing Misparsed Data
I found that 128 rows were incorrectly read in pandas's read_csv function such that `Gender` is incorrectly coded.  conclude the 128 incorrectly coded rows are insignificant compared to the at large 5103596 rows of data read from the CSV file, thus, I remove these rows for convenience in future analysis.

In [11]:
AllMessages['Gender']

0          m
1          m
2          f
3          m
4          m
          ..
5103591    f
5103592    m
5103593    m
5103594    m
5103595    f
Name: Gender, Length: 5103596, dtype: object

In [12]:
AllMessages = AllMessages[(AllMessages.Gender == 'm') | (AllMessages.Gender == 'f')]

In [13]:
AllMessages.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5103468 entries, 0 to 5103595
Data columns (total 5 columns):
 #   Column     Dtype
---  ------     -----
 0   MessageID  object
 1   Province   object
 2   City       object
 3   Gender     object
 4   Message    object
dtypes: object(5)
memory usage: 233.6+ MB

### Changing Data Types
The data types of each column of the data set need to be as following so that SnowNLP can be properly used to analyze the data.
* `Gender`: binary (Male --> 1; Female --> 0)
* `Province`: integer
* `City`: integer
* `MessageID`: integer
* `Message`: unicode string

In [14]:
# recode Gender as binary where male --> 1 and female --> 0
gender = {'m': 1,'f': 0}

AllMessages.Gender = [gender[item] for item in AllMessages.Gender]

In [15]:
# change data type of Province, City, and MessageID from string to integer
AllMessages['Province'] = pd.to_numeric(AllMessages['Province'], errors='ignore')
AllMessages['City'] = pd.to_numeric(AllMessages['City'], errors='ignore')
AllMessages['MessageID'] = pd.to_numeric(AllMessages['MessageID'], errors='ignore')

In [16]:
# change data type of Message from str to unicode string to preserve special characters (Chinese characters)
AllMessages['Message'] = AllMessages['Message'].astype('unicode')

## Subsetting Data by Topic
Now I have selected, cleaned for mis-parsed rows, and applied the correct data types to the full Leiden Weibo Corpus data set. Next I will individually write subsets of the full data set to CSV files which will represent Weibo Corpus pertaining to various topics with corresponding sentiment for each message. I have selected five topics based on an article published in [2013](https://www.chinainternetwatch.com/1899/top-15-most-popular-topics-on-weibo-2012/) by China Internet Watch listing topics widely blogged about on Sina Weibo in 2012. The topics include: the Olympics, Diaoyu/Senkaku Islands, gender types, success, and the government.

In [112]:
# filter rows for each subsetted data set based on topic related keywords
lwc_olympics = AllMessages[AllMessages['Message'].str.contains(u'奥运会')].reset_index(drop=True)
lwc_diaoyu = AllMessages[AllMessages['Message'].str.contains(u'钓鱼岛')].reset_index(drop=True)
lwc_gtypes = AllMessages[AllMessages['Message'].str.contains(u'高富帅|白富美|剩女')].reset_index(drop=True)
lwc_success = AllMessages[AllMessages['Message'].str.contains(u'屌丝')].reset_index(drop=True)
lwc_government = AllMessages[AllMessages['Message'].str.contains(u'政治') & AllMessages['Message'].str.contains(u'腐败')].reset_index(drop=True)

In [114]:
# list of all subsetted datasets
datasets = [lwc_olympics, lwc_diaoyu, lwc_gtypes, lwc_success, lwc_government]

### Adding Sentiment
I use the `SnowNLP` Python library's `str.sentiments` function to add numerical sentiment calculations (0 to 1) for each message in each data set.

In [115]:
# import necessary library
from snownlp import SnowNLP

# adding sentiment for each row of each dataset
for dataset in datasets:
    dataset['Sentiment'] = SnowNLP(dataset['Message'])
    for row in range(len(dataset)):
        dataset['Sentiment'][row] = SnowNLP(dataset['Message'][row]).sentiments

C:\Users\hobbs\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

### Recoding Geographic Locations
The [Leiden Weibo Corpus](http://lwc.daanvanesch.nl/) codes geographic location using numercial indicators that are not easily digestible at first glance. Using the location CSV files provided on the Leiden Weibo Corpus [Open Access Page](http://lwc.daanvanesch.nl/openaccess.php), I recode the message geographic locations accordingly.

In [116]:
# read data tables given my LWC as pandas df and assign column names
df_prov = pd.read_table('lwc_data\meta_provinces.txt', sep=",", names=('Number', 'Province'), encoding='utf-8')
df_city = pd.read_table('lwc_data\meta_cities.txt', sep=",", names=('ID', 'SWprovince', 'SWcity', 'City','Checksum', 'Latitude', 'Longitude', 'SWlocation', 'NumWords', 'NumDistinctWords'), encoding='utf-8')

# convert necessary columns into Python dictionary
provinces = dict([(i, j) for i, j in zip(df_prov.Number, df_prov.Province)])
cities = dict([(i, j) for i, j in zip(df_city.SWcity, df_city.City)])

In [117]:
# recode province for all datasets
lwc_olympics['Province'] = [provinces[item] for item in lwc_olympics.Province]
lwc_diaoyu['Province'] = [provinces[item] for item in lwc_diaoyu.Province]
lwc_gtypes['Province'] = [provinces[item] for item in lwc_gtypes.Province]
lwc_success['Province'] = [provinces[item] for item in lwc_success.Province] 
lwc_government['Province'] = [provinces[item] for item in lwc_government.Province]

In [104]:
# recode city for all datasets (currently has errors)
lwc_olympics['City'] = [cities[item] for item in lwc_olympics.City]
lwc_diaoyu['City'] = [cities[item] for item in lwc_diaoyu.City]
lwc_gtypes['City'] = [cities[item] for item in lwc_gtypes.City]
lwc_success['City'] = [cities[item] for item in lwc_success.City] 
lwc_government['City'] = [cities[item] for item in lwc_government.City]

In [118]:
lwc_olympics

,MessageID,Province,City,Gender,Message,Sentiment
0,3399708783612028,Guǎngdōng 广东,3,1,#羽毛球#新年第一战，风云组合终于赢了李龙大郑再成，可惜林丹却败给了李崇伟，难道预示着今年伦...,0.960635
1,3399760788465017,Guǎngdōng 广东,8,1,忽然听说今年有奥运会，才感觉四年时间，一眨眼过去了。偶然又听到《2002年的第一场雪》，才感...,0.996456
2,3399855461063883,Héběi 河北,4,1,NBA超级巨星科比-布莱恩特领衔2012伦敦奥运会美国男篮“梦之队”。科比、詹姆斯、韦德、波...,0.999999
3,3399882062752246,Qítā 其他,1000,1,科比现在都34岁了今年 北京奥运会的时候就三十岁了 什么才31啊 看直播： http:/...,0.527577
4,3399906973048091,Hǎiwài 海外,1000,0,忽然听说今年有奥运会，才感觉四年时间，一眨眼过去了。偶然又听到《2002年的第一场雪》，才感...,0.989281
...,...,...,...,...,...,...
333,3407194895077098,Zhèjiāng 浙江,1,0,午后 宁宁吵着让我讲她小时候的故事 矮油 天天说自己已经是大人的妞 受不了你 那就说说你出生...,0.999999
334,3407221251870929,Xīnjiāng 新疆,1,1,对于环保的设计目前已经延伸到了奥运会上，目前公布的2010年温哥华冬奥会奖牌将是环保的奖牌，...,0.927025
335,3407243804383053,Liáoníng 辽宁,1,1,分享图片1980年夏季奥运会 吉祥物,0.755597
336,3407285932155175,Hǎiwài 海外,3,0,以前就听雷声提过打Joppich费劲的事儿。所以我之前的微博说奥运会前希望雷声多碰Joppi...,0.997008
337,3407305763171449,Hǎiwài 海外,7,1,德约科维奇，今年奥运会希望你不要再拿季军了，要有进步，费德勒希望你在今年最后一年奥运会能拿冠...,0.999016

In [120]:
# write all data sets to csv
lwc_olympics.to_csv('lwc_olympics.csv', index=False, encoding='utf-8')
lwc_diaoyu.to_csv('lwc_diaoyu.csv', index=False, encoding='utf-8')
lwc_gtypes.to_csv('lwc_gtypes.csv', index=False, encoding='utf-8')
lwc_success.to_csv('lwc_success.csv', index=False, encoding='utf-8')
lwc_government.to_csv('lwc_government.csv', index=False, encoding='utf-8')